services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    networks:
      - config-store-net
    command: npm run dev

networks:
  config-store-net:
