version: "3.1"
services:
   gol:
    build: ./gol
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: gollog
        target: /data
    networks:
      - mynetwork

   spc:
    build: ./spc
    ports:
      - 8081:8080
    volumes:
      - type: volume
        source: spclog
        target: /data
    networks:
      - mynetwork
 

volumes:
  gollog:
  spclog:

networks:
  mynetwork:
   driver: bridge

